// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9w-U4z_yMQuErj8BeEDdcbUxtRwd0_SU',
    appId: '1:203754512294:web:51e75ed053497e39c0f967',
    messagingSenderId: '203754512294',
    projectId: 'donationlogin-b1ab8',
    authDomain: 'donationlogin-b1ab8.firebaseapp.com',
    storageBucket: 'donationlogin-b1ab8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwO7uvxjyZgM1To8QtFvRZC0Gnua9mLmM',
    appId: '1:203754512294:android:a589217aa3542241c0f967',
    messagingSenderId: '203754512294',
    projectId: 'donationlogin-b1ab8',
    storageBucket: 'donationlogin-b1ab8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCps6-a7zVQyR1_FtWJPKEmzWi25kyuDlc',
    appId: '1:203754512294:ios:3712bfbecacd4e3fc0f967',
    messagingSenderId: '203754512294',
    projectId: 'donationlogin-b1ab8',
    storageBucket: 'donationlogin-b1ab8.firebasestorage.app',
    iosBundleId: 'com.example.myDonationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCps6-a7zVQyR1_FtWJPKEmzWi25kyuDlc',
    appId: '1:203754512294:ios:3712bfbecacd4e3fc0f967',
    messagingSenderId: '203754512294',
    projectId: 'donationlogin-b1ab8',
    storageBucket: 'donationlogin-b1ab8.firebasestorage.app',
    iosBundleId: 'com.example.myDonationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9w-U4z_yMQuErj8BeEDdcbUxtRwd0_SU',
    appId: '1:203754512294:web:f6f7a6f503736ec5c0f967',
    messagingSenderId: '203754512294',
    projectId: 'donationlogin-b1ab8',
    authDomain: 'donationlogin-b1ab8.firebaseapp.com',
    storageBucket: 'donationlogin-b1ab8.firebasestorage.app',
  );
}


// 6LejVgArAAAAAKMhmybcSR4S_Mxjv3q7BxS0rzZg site key for recaptcha
//6LejVgArAAAAAJZMz_KnGKe9BviVtzjuC8v1g5xW secret key for recaptcha